### ISSUE TITLE
widget dispose error

### ISSUE THREAD

**Issue by hjc22** [florent37/Flutter-Anim#2]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: This ticker was canceled: _WidgetTicker(created by _TimerBarState#c5d53(lifecycle state: created, tickers: tracking 1 ticker))
E/flutter (18394): #0      SimpleAnimatable.play (package:money_topic/components/anim/animatable.dart:94:5)
E/flutter (18394): <asynchronous suspension>
E/flutter (18394): #1      ChainAnimatable.play (package:money_topic/components/anim/animatable.dart:169:24)
E/flutter (18394): <asynchronous suspension>
E/flutter (18394): #2      TogetherAnimatable.play (package:money_topic/components/anim/animatable.dart:124:40)
E/flutter (18394): <asynchronous suspension>
E/flutter (18394): #3      Anim._start (package:money_topic/components/anim/anim.dart:173:25)

**Comment by hjc22** [comment]
my code:    
 
dispose(){  
  anim.dispose();   
  super.dispose(); 
}
